name: Release

on:
  workflow_dispatch:
    inputs:
      publish-tag:
        description: 'The tag to publish'
        required: true
        type: string

concurrency:
  group: release

env:
  CI: true
  FORCE_COLOR: 1
  JAVA_VERSION: "21"

jobs:
  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
            java-version: ${{ env.JAVA_VERSION }}
            distribution: "temurin"
    
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4 
        
      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew assembleRelease --stacktrace
        
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ inputs.publish-tag }}
          files: app/build/outputs/apk/release/*.apk
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


